language: python
sudo: false
dist: precise
cache: pip
git:
   depth: 1
python:
- 2.6
- 2.7
- 3.3
- 3.4
- 3.5
- 3.6
- pypy
env:
- secure: "EhG2uSD2m1eGxuL2HeQewJJx7MVL4WpjrxyfiUBEgsApemD1yKJPjUnLwAyd\nbPi5HJx5ySm1TTRSvj6/yP85YLYTaJHA8OabKk7p0wFW294qcrYIDGovU7NL\n3YOqZmqN+S3XOBGFCOnByxE+pcxxWW/3/I09EgeW7D6tBPh67G0="
install:
- echo $TRAVIS_PYTHON_VERSION
- pip install psutil coveralls flake8 memory_profiler
- >
    if [[ "$TRAVIS_PYTHON_VERSION" != "pypy" ]]; then
      pip install 'pytest-cov>=1.8.0';
    fi
- >
    if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
      pip install --upgrade setuptools;
    fi
- pip install -e .[test] --upgrade
script:
- python -mwand.version --verbose
- >
    if [[ "$TRAVIS_PYTHON_VERSION" == "pypy" || "$TRAVIS_PYTHON_VERSION" == "pypy3" ]]; then
      py.test --boxed --durations=20;
    else
      py.test --cov wand --boxed --durations=20;
    fi
- >
    if [[ "$TRAVIS_PYTHON_VERSION" != "2.6" ]]; then
      flake8 --ignore=E722 .;
    fi
after_success:
- coveralls
