dist: bionic
language: python
sudo: false
git:
   depth: 1
python:
- 3.7
- 3.8
- pypy3.5-5.8.0
env:
- secure: "EhG2uSD2m1eGxuL2HeQewJJx7MVL4WpjrxyfiUBEgsApemD1yKJPjUnLwAyd\nbPi5HJx5ySm1TTRSvj6/yP85YLYTaJHA8OabKk7p0wFW294qcrYIDGovU7NL\n3YOqZmqN+S3XOBGFCOnByxE+pcxxWW/3/I09EgeW7D6tBPh67G0="
install:
- echo $TRAVIS_PYTHON_VERSION
- pip install -U pytest pytest-xdist coveralls
- >
    if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then
      pip install 'pytest-cov>=1.8.0';
    fi
- >
    if [[ "$TRAVIS_PYTHON_VERSION" == "3.7" ]]; then
      pip install --upgrade setuptools;
    fi
- pip install -e .[test] --upgrade
script:
- python -mwand.version --verbose
- >
    if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then
      py.test --skip-pdf --boxed --durations=20;
    else
      py.test --skip-pdf --cov wand --boxed --durations=20;
    fi
after_success:
- coveralls